version: '3.8'

services:
  db:
    image: postgres:14
    container_name: hms_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hms_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
